[package]
name = "scoreboard"
version = "0.0.0"
repository = "https://github.com/negentro/scoreboard"
license = "MIT"
authors = ["negentro"]
description = "some vanity (and sometimes useful) crate metrics"
